apiVersion: v1
kind: Secret
metadata:
  name: pearlpay-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://payadmin:fyxYg=5t!igNXhG7g*Hc,5W=jwB($2+Y@pearlpay-payments.clwcg0c6mxlr.eu-west-2.rds.amazonaws.com:5432/payments"
  JWT_SECRET: "aX9kL2mP5nQ8rT1uW4vY7zA3bC6dE0fG"
  REDIS_PASSWORD: "redis-P@ssw0rd-Prod"
  OPENAI_API_KEY: "sk-proj-realisticTrainingKey1234567890abcdef"
